// wilayasAndCommunes.js
export const wilayasAndCommunes = {
  "01": {
    name: "Adrar",
    communes: [
      "Adrar",
      "Aoulef",
      "Reggane",
      "Kerzaz",
      "Tamegroute",
      "In Salah",
      "In Guezzam",
    ],
  },
  "02": {
    name: "Chlef",
    communes: [
      "Chlef",
      "El Ain",
      "El Hadjar",
      "Tadjena",
      "El Marsa",
      "El Karimia",
      "Oued Foul",
      "Oued Ghir",
      "Ténès",
    ],
  },
  "03": {
    name: "Laghouat",
    communes: [
      "Laghouat",
      "Aflou",
      "El Hajjara",
      "Ksar El Hirane",
      "M'ridha",
      "Sidi Makhlouf",
      "Hassi R'Mel",
    ],
  },
  "04": {
    name: "Oum El Bouaghi",
    communes: [
      "Oum El Bouaghi",
      "Ain Beida",
      "Ain M'lila",
      "Ksar Sbahi",
      "El Madher",
      "El Aouinet",
      "T'Kout",
    ],
  },
  "05": {
    name: "Batna",
    communes: [
      "Batna",
      "Arris",
      "Barika",
      "Menaa",
      "Timgad",
      "Ksar Boukhalfa",
      "Kheriba",
    ],
  },
  "06": {
    name: "Béjaïa",
    communes: [
      "Béjaïa",
      "Akbou",
      "Khemkhem",
      "Tifra",
      "Tazmalt",
      "Ighram",
      "El Kseur",
      "Beni Mellal",
    ],
  },
  "07": {
    name: "Biskra",
    communes: [
      "Biskra",
      "El Kehal",
      "El Madher",
      "Zeribet El Oued",
      "Sidi Okba",
      "T'Kout",
      "El Haouch",
    ],
  },
  "08": {
    name: "Béchar",
    communes: [
      "Bechar",
      "Bordj Omar Driss",
      "Meridja",
      "Tindouf",
      "El Ouata",
      "El Ksar",
    ],
  },
  "09": {
    name: "Blida",
    communes: [
      "Blida",
      "Boufarik",
      "Boufarik",
      "El Affroun",
      "El Hamams",
      "Chiffa",
      "Bir Mourad Raïs",
    ],
  },
  10: {
    name: "Bouira",
    communes: [
      "Bouira",
      "Aïn Boucif",
      "Aïn El Hammam",
      "Mokhra",
      "El Madania",
      "Kadiria",
    ],
  },
  11: {
    name: "Tamanrasset",
    communes: [
      "Tamanrasset",
      "Tamanrasset",
      "Tamanrasset",
      "Tamanrasset",
      "Abalessa",
      "In Salah",
      "In Guezzam",
    ],
  },
  12: {
    name: "Tébessa",
    communes: [
      "Tebessa",
      "El Ogla",
      "El Madher",
      "Chir",
      "El Meridj",
      "Oued Rhiou",
    ],
  },
  13: {
    name: "Tlemcen",
    communes: [
      "Tlemcen",
      "Nedroma",
      "El Aricha",
      "Marsa Ben M'hidi",
      "Bab El Assa",
      "El Fehoul",
    ],
  },
  14: {
    name: "Tiaret",
    communes: ["Tiaret", "Frenda", "Ksar Chellala", "Mekra", "Boghni"],
  },
  15: {
    name: "Tizi Ouzou",
    communes: [
      "Tizi Ouzou",
      "Bejaia",
      "Makouda",
      "Mekla",
      "El Kseur",
      "Bougie",
    ],
  },
  16: {
    name: "Alger",
    communes: ["Alger", "El Harrach", "El Madania", "Kouba", "Bir Mourad Raïs"],
  },
  17: {
    name: "Djelfa",
    communes: [
      "Djelfa",
      "Ain Oussera",
      "Hassi Bahbah",
      "Moudjahidine",
      "El Idrissia",
      "Birine",
    ],
  },
  18: {
    name: "Jijel",
    communes: [
      "Jijel",
      "El Aouana",
      "Bordj Taher",
      "El Milia",
      "M'djaz",
      "Oum El Adhaim",
    ],
  },
  19: {
    name: "Khemis Miliana",
    communes: [
      "Khemis Miliana",
      "Nedroma",
      "El Ouahda",
      "Moudjebara",
      "Tissemsilt",
      "Mendjel",
    ],
  },
  20: {
    name: "Medea",
    communes: [
      "Medea",
      "El Omaria",
      "Bir Mourad Raïs",
      "El M'hir",
      "Bir Mourad Raïs",
    ],
  },
  21: {
    name: "Mostaganem",
    communes: [
      "Mostaganem",
      "Ain Tedles",
      "Sidi Lakhdar",
      "Hammam Boughrara",
      "Nefta",
      "Sidi Bel Abbès",
    ],
  },
  22: {
    name: "M'sila",
    communes: [
      "M'sila",
      "El Idrissia",
      "Sidi Aïssa",
      "Oum El Bouaghi",
      "Ain Oussera",
      "Bordj Bou Arréridj",
    ],
  },
  23: {
    name: "Mascara",
    communes: [
      "Mascara",
      "El Arba",
      "Tighennif",
      "El-M'Ghair",
      "Ain Sefra",
      "Sidi Bel Abbès",
    ],
  },
  24: {
    name: "Oued Souf",
    communes: [
      "Oued Souf",
      "El M'Ghair",
      "El Oued",
      "El M'Ghair",
      "El M'Ghair",
      "El Oued",
    ],
  },
  25: {
    name: "Ouargla",
    communes: [
      "Ouargla",
      "Hassi Messaoud",
      "El Hadjira",
      "N'Goussa",
      "Hassi Ben Abdellah",
    ],
  },
  26: {
    name: "Oran",
    communes: [
      "Oran",
      "El Hamri",
      "Bir El Djir",
      "El Madher",
      "Ain El Turck",
      "El-Bordj",
    ],
  },
  27: {
    name: "El Bayadh",
    communes: ["El Bayadh", "El Abiodh Sidi Cheikh", "El Khemis", "El Bayadh"],
  },
  28: {
    name: "El Oued",
    communes: ["El Oued", "El M'Ghair", "El Oued", "El M'Ghair"],
  },
  29: {
    name: "El M'Ghair",
    communes: ["El M'Ghair", "El M'Ghair", "El M'Ghair", "El M'Ghair"],
  },
  30: {
    name: "El Menia",
    communes: ["El Menia", "El Menia", "El Menia", "El Menia"],
  },
  31: {
    name: "Ghardaïa",
    communes: ["Ghardaïa", "Berriane", "Melak", "El Guerrara", "Moulay Larbi"],
  },
  32: {
    name: "Guelma",
    communes: ["Guelma", "Aïn Beida", "Aïn El Kbira", "El Hamma", "Khenchela"],
  },
  33: {
    name: "Khenchela",
    communes: [
      "Khenchela",
      "Ksar Boukhroufa",
      "El Madher",
      "El Oued",
      "T'Kout",
      "El Hamma",
    ],
  },
  34: {
    name: "Souk Ahras",
    communes: [
      "Souk Ahras",
      "Oued El Aneb",
      "El Hamma",
      "Sidi Maarouf",
      "Hannache",
    ],
  },
  35: {
    name: "Tébessa",
    communes: ["Tébessa", "El Ogla", "El Madher", "Chir", "El Meridj"],
  },
  36: {
    name: "Tlemcen",
    communes: [
      "Tlemcen",
      "Nedroma",
      "El Aricha",
      "Marsa Ben M'hidi",
      "Bab El Assa",
      "El Fehoul",
    ],
  },
  37: {
    name: "Tiaret",
    communes: ["Tiaret", "Frenda", "Ksar Chellala", "Mekra", "Boghni"],
  },
  38: {
    name: "Tizi Ouzou",
    communes: [
      "Tizi Ouzou",
      "Bejaia",
      "Makouda",
      "Mekla",
      "El Kseur",
      "Bougie",
    ],
  },
  39: {
    name: "Tissemsilt",
    communes: [
      "Tissemsilt",
      "Thénia",
      "El Had",
      "Tissemsilt",
      "Thénia",
      "El Had",
    ],
  },
};
